export const categories = [
  { id: "all", name: "All Homes", icon: "Home" },
  { id: "cabin", name: "Cabins", icon: "Tent" },
  { id: "treehouse", name: "Treehouses", icon: "Trees" },
  { id: "cottage", name: "Cottages", icon: "Warehouse" },
  { id: "apartment", name: "Eco Apts", icon: "Building2" },
];

export const listings = [
  {
    id: 1,
    title: "The Green Loft",
    location: "Portland, Oregon",
    price: 145,
    rating: 4.92,
    reviews: 128,
    image: "/images/listing-1.png",
    category: "apartment",
    tags: ["Eco-friendly", "City Center"],
  },
  {
    id: 2,
    title: "Sunflower Cottage",
    location: "Cotswolds, UK",
    price: 210,
    rating: 4.98,
    reviews: 85,
    image: "/images/listing-2.png",
    category: "cottage",
    tags: ["Garden", "Historic"],
  },
  {
    id: 3,
    title: "Canopy Retreat",
    location: "Bali, Indonesia",
    price: 350,
    rating: 5.0,
    reviews: 42,
    image: "/images/listing-3.png",
    category: "treehouse",
    tags: ["Luxury", "Nature"],
  },
  {
    id: 4,
    title: "Forest Edge Cabin",
    location: "Vancouver, BC",
    price: 180,
    rating: 4.85,
    reviews: 210,
    image: "/images/hero-cabin.png",
    category: "cabin",
    tags: ["Secluded", "Hiking"],
  },
  {
    id: 5,
    title: "Solar Powered Villa",
    location: "Tuscany, Italy",
    price: 295,
    rating: 4.95,
    reviews: 67,
    image: "/images/listing-2.png",
    category: "cottage",
    tags: ["Sustainable", "Vineyard"],
  },
  {
    id: 6,
    title: "Urban Jungle Studio",
    location: "Berlin, Germany",
    price: 110,
    rating: 4.78,
    reviews: 315,
    image: "/images/listing-1.png",
    category: "apartment",
    tags: ["Nightlife", "Modern"],
  },
];