export const categories = [      
  { id: "all", name: "All Experiences", icon: "Compass" },     
  { id: "coffee", name: "Coffee Ceremony", icon: "Coffee" },  
  { id: "foods", name: "Local Foods", icon: "UtensilsCrossed" },  
  { id: "dances", name: "Local Dances", icon: "Music" },    
  { id: "crafts", name: "Crafts", icon: "Palette" },
  { id: "clothing", name: "Clothing", icon: "Shirt" },
];

export const listings = [    
  {
    id: 1,    
    title: "Traditional Coffee Ceremony",
    location: "Addis Ababa",
    meetingPoint: "Bole, Addis Ababa",
    lat: 8.9806,
    lng: 38.7578,
    price: 45,  
    rating: 4.98,
    reviews: 234,   
    image: "/images/coffee-ceremony-experience.png",
    category: "coffee",
    description: "Experience the ancient Ethiopian coffee ceremony (Buna) with local hosts in their home. Learn the preparation ritual, roasting, grinding, and brewing methods that have been passed down through generations.",
    tags: ["Cultural", "Traditional"],
  },
  {
    id: 2,
    title: "Injera Bread Making",
    location: "Addis Ababa",
    meetingPoint: "Piazza, Addis Ababa",
    lat: 9.032,
    lng: 38.748,
    price: 38,
    rating: 4.95,
    reviews: 187,
    image: "/images/injera-experience.png",
    category: "foods",
    description: "Master the art of making authentic Injera, Ethiopia's iconic sourdough flatbread. Learn the fermentation process and prepare traditional meals with your host family.",
    tags: ["Cooking", "Family"],
  },
  {
    id: 3,
    title: "Doro Wot Cooking Class",
    location: "Dire Dawa",
    meetingPoint: "Kezira, Dire Dawa",
    lat: 9.6,
    lng: 41.8667,
    price: 42,
    rating: 4.96,
    reviews: 156,
    image: "/images/doro-wot-experience.png",
    category: "foods",
    description: "Prepare the beloved Doro Wot, a spiced chicken stew that represents the heart of Ethiopian cuisine. Cook alongside a local chef using traditional recipes and authentic spices.",
    tags: ["Cooking", "Spiced"],
  },
  {
    id: 4,
    title: "Azmari Dance Experience",
    location: "Addis Ababa",
    meetingPoint: "Kazanchis, Addis Ababa",
    lat: 9.0054,
    lng: 38.7636,
    price: 50,
    rating: 5.0,
    reviews: 203,
    image: "/images/dance-experience.png",
    category: "dances",
    description: "Join a lively evening of traditional Azmari dancing and live music. Learn the shoulder-shaking movements and celebrate Ethiopian culture with local musicians and dancers.",
    tags: ["Entertainment", "Live Music"],
  },
  {
    id: 5,
    title: "Traditional Basket Weaving",
    location: "Bahir Dar",
    meetingPoint: "Lake Tana, Bahir Dar",
    lat: 11.5936,
    lng: 37.3908,
    price: 35,
    rating: 4.92,
    reviews: 128,
    image: "/images/crafts-experience.png",
    category: "crafts",
    description: "Discover the ancient art of Ethiopian basket weaving with master craftspeople. Create your own traditional basket using natural materials and centuries-old techniques.",
    tags: ["Artisan", "Hands-on"],
  },
  {
    id: 6,
    title: "Habesha Clothing Styling",
    location: "Addis Ababa",
    meetingPoint: "Sarbet, Addis Ababa",
    lat: 9.0108,
    lng: 38.722,
    price: 40,
    rating: 4.94,
    reviews: 92,
    image: "/images/clothing-experience.png",
    category: "clothing",
    description: "Wear and learn about traditional Habesha clothing. Local experts teach you about the embroidered shawls (netela), traditional dresses, and their cultural significance.",
    tags: ["Fashion", "Cultural"],
  },
  {
    id: 7,
    title: "Advanced Coffee Roasting",
    location: "Hawassa",
    meetingPoint: "Lake Hawassa, Hawassa",
    lat: 7.0621,
    lng: 38.4763,
    price: 55,
    rating: 4.99,
    reviews: 89,
    image: "/images/coffee-ceremony-experience.png",
    category: "coffee",
    description: "Deep dive into coffee roasting with local coffee farmers. Visit their farm, roast beans traditionally, and understand the journey from seed to cup.",
    tags: ["Agricultural", "Farm Visit"],
  },
  {
    id: 8,
    title: "Multi-Course Ethiopian Feast",
    location: "Gondar",
    meetingPoint: "Fasil Ghebbi, Gondar",
    lat: 12.6,
    lng: 37.4667,
    price: 60,
    rating: 4.97,
    reviews: 145,
    image: "/images/injera-experience.png",
    category: "foods",
    description: "Enjoy a comprehensive Ethiopian dining experience with multiple traditional dishes. Learn about each course and its place in Ethiopian culinary heritage.",
    tags: ["Feast", "Multi-Course"],
  },
  {
    id: 9,
    title: "Contemporary Dance Fusion",
    location: "Addis Ababa",
    meetingPoint: "Meskel Square, Addis Ababa",
    lat: 9.0106,
    lng: 38.761,
    price: 48,
    rating: 4.93,
    reviews: 67,
    image: "/images/dance-experience.png",
    category: "dances",
    description: "Blend traditional Ethiopian dance moves with contemporary choreography. Learn from professional dancers in an interactive workshop.",
    tags: ["Modern", "Workshop"],
  },
  {
    id: 10,
    title: "Pottery & Clay Crafting",
    location: "Lalibela",
    meetingPoint: "Rock-Hewn Churches, Lalibela",
    lat: 12.0322,
    lng: 39.0476,
    price: 36,
    rating: 4.91,
    reviews: 73,
    image: "/images/crafts-experience.png",
    category: "crafts",
    description: "Create traditional Ethiopian pottery using clay and hand-molding techniques. Perfect your craft under expert guidance in a rural village setting.",
    tags: ["Artisan", "Village"],
  },
  {
    id: 11,
    title: "Shama Dress Workshop",
    location: "Dire Dawa",
    meetingPoint: "Railway Station, Dire Dawa",
    lat: 9.5931,
    lng: 41.8647,
    price: 38,
    rating: 4.89,  
    reviews: 54,
    image: "/images/clothing-experience.png",
    category: "clothing",
    description: "Learn about traditional Ethiopian Shama dresses with intricate patterns. Understand the symbolism and weaving heritage behind these stunning garments.",
    tags: ["Traditional", "Weaving"],
  },
  {
    id: 12,  
    title: "Spice Market & Food Tour",    
    location: "Addis Ababa",  
    meetingPoint: "Merkato, Addis Ababa",    
    lat: 9.035,  
    lng: 38.7469,
    price: 32,
    rating: 4.96,
    reviews: 118,   
    image: "/images/doro-wot-experience.png",
    category: "foods",
    description: "Explore local spice markets with a knowledgeable guide. Discover authentic Ethiopian spices and learn how they're used in traditional cooking.",
    tags: ["Market Tour", "Spices"],
  },
  {
    id: 13,
    title: "Wolaita Tire Siga Beef Stew",
    location: "Wolaita",    
    meetingPoint: "Sodo Town Center, Wolaita",    
    lat: 6.9,
    lng: 37.75,
    price: 48,
    rating: 4.95,
    reviews: 91,
    image: "/images/doro-wot-experience.png",
    category: "foods",
    description: "Savor authentic Wolaita tire siga, a slow-cooked beef stew with local spices and herbs. Experience this regional specialty directly from a Wolaita family's kitchen.",
    tags: ["Regional", "Food Tasting"],
  },
  {
    id: 14,
    title: "Gurage Kitfo Feast",
    location: "Butajira",    
    meetingPoint: "Butajira Town, Gurage Zone",    
    lat: 8.1468,
    lng: 38.075,
    price: 50,
    rating: 4.97,
    reviews: 99,
    image: "/images/doro-wot-experience.png",
    category: "foods",
    description: "Enjoy freshly prepared Gurage kitfo with traditional accompaniments. Learn how this celebrated raw meat dish is prepared with care and seasoning by local masters.",
    tags: ["Cultural", "Dining"],
  },
  {
    id: 15,
    title: "Local Food Tasting Experience",
    location: "Addis Ababa",   
    meetingPoint: "Piazza District",   
    lat: 9.032,
    lng: 38.748,
    price: 40,
    rating: 4.94,
    reviews: 105,
    image: "/images/injera-experience.png",
    category: "foods",
    description: "Taste a variety of traditional Ethiopian dishes in an intimate setting with a local host. From hearty stews to spiced vegetables, discover the full range of authentic flavors.",
    tags: ["Tasting", "Variety"],
  },
  {
    id: 16,
    title: "Traditional Ethiopian Coffee Ritual",
    location: "Hawassa",
    meetingPoint: "Lake Hawassa, Hawassa",    
    lat: 7.0621,
    lng: 38.4763,
    price: 55,
    rating: 4.99,
    reviews: 88,
    image: "/images/ethiopian-coffee.png",
    category: "coffee",
    description: "Participate in the full Ethiopian coffee ceremony ritual. Watch coffee beans roast over open flame, learn traditional grinding and brewing techniques passed down for generations.",
    tags: ["Coffee", "Ritual"],
  },
  {
    id: 17,
    title: "Merkato Market Walking Tour",
    location: "Addis Ababa",   
    meetingPoint: "Merkato Main Gate",   
    lat: 9.035,
    lng: 38.7469,
    price: 35,
    rating: 4.93,
    reviews: 112,
    image: "/images/crafts-experience.png",
    category: "foods",
    description: "Explore one of Africa's largest markets with a knowledgeable local. Discover traditional goods, spices, clothing, and local delicacies while learning market traditions.",
    tags: ["Market Tour", "Local"],
  },
];
 